<link href="css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="js/ajax.js"></script>
<script src="css/dist/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/dist/sweetalert.css">

<center><font size="3"><strong>
<div class="table-responsive" style="width:1100px;" > 
  <table style="background-color: transparent;color:white;border-top-color: transparent;" class="table table-condensed" align="center">  
  
  <div class="row">
  <div class="col-md-2" style="color:white">
     <button type="button" onclick="Nuevo();" class="btn btn-primary" >
     Nuevo Contanto
  </button>
  <br><br>
  </div>

  <tr>
    <th>Nombre  </th>
    <th>Telefono 1 </th>
    <th>Telefono 2 </th>
    <th>E-mail  </th>
    <th>Direccion  </th>
  </tr>
  <?php foreach ( $this->contactos as $contacto): ?>
    <tr>
      <td><?php echo $contacto['nombre']; ?></td>
      <td><?php echo $contacto['telefono1']; ?></td>
      <td><?php echo $contacto['telefono2']; ?></td>
      <td><?php echo $contacto['email']; ?></td>
      <td><?php echo $contacto['direccion']; ?></td>
      <td>
        <a onclick="Editar('<?php echo $contacto['id']; ?>','<?php echo $contacto['nombre']; ?>','<?php echo $contacto['telefono1']; ?>','<?php echo $contacto['telefono2']; ?>','<?php echo $contacto['email']; ?>','<?php echo $contacto['direccion']; ?>');"> Editar </a>
      </td>
      <td>
        <a onclick="Eliminar('<?php echo $contacto['id']; ?>');" style="color:#FE2E64"  > Eliminar </a>
      </td>
    </tr>
    <?php endforeach;?>
  </table>
</div>
</strong></font></center>

<center><div  class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="background-image:url(img/nota2.png);background-size: cover;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"  style="text-align:center; color:white;">Guardar Contacto</h4>
      </div><br><br>
      <form role="form" action="" name="Contactos" onsubmit="Registrar(idC,accion); return false">
        
        <div class="col-lg-12">
          <div class="form-group">
            <label>Nombre</label>
            <input name="nombre" class="form-control" required>
          </div>

          <div class="form-group">
            <label>Telefono 1</label>
            <input type="number" name="telefono1" class="form-control" style="width:280px;" required>
          </div>

          <div class="form-group">
            <label>Telefono 2</label>
            <input type="number" name="telefono2" class="form-control" style="width:280px;">
          </div>

          <div class="form-group">
            <label>E-mail</label>
            <input  type="email" name="email" class="form-control" required>
          </div>

          <div class="form-group">
            <label>Direccion</label>
            <input name="direccion" class="form-control" required>
          </div>

          <button type="submit" class="btn btn-info btn-lg">
            <span  aria-hidden="true"></span> Registrar
          </button>

        </div>
      </form>
      <div class="modal-footer">
      <button type="button" class="btn btn-danger btn-circle" data-dismiss="modal"><i class=""></i>x</button>
      </div>
    </div>
  </div>
</div>

<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript">
  var accion;
  var idC;
  function Nuevo(){
    accion='N';
    document.Contactos.nombre.value="";
    document.Contactos.telefono1.value="";
    document.Contactos.telefono2.value="";
    document.Contactos.email.value="";
    document.Contactos.direccion.value="";
    $('#modal').modal('show');
    
  }

  function Editar(id,nombre,telefono1,telefono2,email,direccion){
    accion='E';
    idC=id;
    document.Contactos.nombre.value=nombre;
    document.Contactos.telefono1.value=telefono1;
    document.Contactos.telefono2.value=telefono2;
    document.Contactos.email.value=email;
    document.Contactos.direccion.value=direccion;

    $('#modal').modal('show');
  }
</script>

<br>
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="color:#2E2EFE">
    <?php  
      echo $this->paginationControl($this->contactos,  
        'Sliding',  
        'index/pagination/pagination_control.phtml');  
    ?>  
  </div>
</div>
