
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Aplicacion Agenda</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>


  <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		
		<link rel="stylesheet" href="css/layers.min.css" media="screen">
		<link rel="stylesheet" href="css/font-awesome.min.css" media="screen"> 
		<link rel="stylesheet" href="css/style.css" media="screen">
		<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
		<link rel="icon" href="favicon.ico">
		<link rel="stylesheet" type="text/css" href="css/dist/sweetalert.css">
		<link rel="stylesheet" type="text/css" href="themes/twitter.css">

		
</head>
<body style="background-image:url(img/fondo.jpg);">
	 

<div id="header" style="background-color: transparent; height: 50px;">
    
       <a id="menu-toggle" href="#"><i class="fa fa-bars fa-lg"></i></a>
					<nav>
						<ul class="" role="navigation">
							<li class="menu-item">
								<a href="">INCIO</a>
								
							</li>
						</ul>
						
						<ul class="" role="navigation">
							<li class="menu-item">
								<a onclick="Info()">CONTACTO</a>
								
							</li>
						</ul>
					</nav>
    </div>



    <div  class="modal fade" id="informacion" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" style="text-align:center">Contacto</h4>
            </div><br><br>
           	<center><tr>
		        <th>Nombre : Julio César Vásquez Hernández</th><br><br>
		        <th>Telefono: 5525782957 </th><br><br>
		        <th>E-mail : cesarvasquez12@hotmail.com </th><br><br>
		    </tr></center>
          </div>
        </div>
      </div>






    
    <script type="text/javascript">
    function Info(){
    	$('#informacion').modal('show');
    }
    </script>

 
<?php echo $this->layout()->content; ?>
 
</body>
</html>